import { z } from "zod";
import type { EndpointDef } from "../types.js";

const MSG_LIST_SELECT =
  "id,subject,from,toRecipients,ccRecipients,receivedDateTime,sentDateTime,bodyPreview,hasAttachments,importance,isRead,conversationId,internetMessageId,webLink";

const FOLDER_SELECT = "id,displayName,parentFolderId,childFolderCount,unreadItemCount,totalItemCount";

export const mailEndpoints: EndpointDef[] = [
  {
    name: "list-mail-messages",
    description:
      "List/search messages in the signed-in user's mailbox. Supports full-text KQL search (sender, recipient, cc, subject, keyword, attachment, read/unread, importance) and time ranges.",
    toolset: "mail",
    scopes: ["Mail.Read"],
    method: "GET",
    path: "/me/messages",
    resourceType: "mailMessage",
    paginated: true,
    defaultSelect: MSG_LIST_SELECT,
    defaultOrderby: "receivedDateTime desc",
    query: { filter: true, search: true, orderby: true, select: true },
    timeFilterProperty: "receivedDateTime",
    kqlTime: true,
    sourceType: "mailMessage",
  },
  {
    name: "get-mail-message",
    description: "Get a single message including its full body.",
    toolset: "mail",
    scopes: ["Mail.Read"],
    method: "GET",
    path: "/me/messages/{messageId}",
    resourceType: "mailMessage",
    query: { select: true },
    sourceType: "mailMessage",
  },
  {
    name: "list-mail-folders",
    description: "List top-level mail folders of the signed-in user's mailbox.",
    toolset: "mail",
    scopes: ["Mail.Read"],
    method: "GET",
    path: "/me/mailFolders",
    resourceType: "mailFolder",
    paginated: true,
    defaultSelect: FOLDER_SELECT,
  },
  {
    name: "list-mail-child-folders",
    description: "List child folders of a mail folder.",
    toolset: "mail",
    scopes: ["Mail.Read"],
    method: "GET",
    path: "/me/mailFolders/{folderId}/childFolders",
    pathParamDescriptions: { folderId: "Mail folder id (from list-mail-folders)" },
    resourceType: "mailFolder",
    paginated: true,
    defaultSelect: FOLDER_SELECT,
  },
  {
    name: "list-mail-folder-messages",
    description: "List/search messages inside a specific mail folder.",
    toolset: "mail",
    scopes: ["Mail.Read"],
    method: "GET",
    path: "/me/mailFolders/{folderId}/messages",
    pathParamDescriptions: { folderId: "Mail folder id" },
    resourceType: "mailMessage",
    paginated: true,
    defaultSelect: MSG_LIST_SELECT,
    defaultOrderby: "receivedDateTime desc",
    query: { filter: true, search: true, orderby: true, select: true },
    timeFilterProperty: "receivedDateTime",
    kqlTime: true,
    sourceType: "mailMessage",
  },
  {
    name: "list-mail-attachments",
    description: "List attachments of a message (metadata only: name, contentType, size).",
    toolset: "mail",
    scopes: ["Mail.Read"],
    method: "GET",
    path: "/me/messages/{messageId}/attachments",
    resourceType: "mailAttachment",
    paginated: true,
    defaultSelect: "id,name,contentType,size,isInline,lastModifiedDateTime",
  },
  {
    name: "get-mail-attachment-content",
    description:
      "Download an attachment and return its content. DOCX/XLSX/PPTX/PDF/TXT/CSV are converted to text; other binaries (images) come back as base64.",
    toolset: "mail",
    scopes: ["Mail.Read"],
    method: "GET",
    path: "/me/messages/{messageId}/attachments/{attachmentId}/$value",
    resourceType: "mailAttachment",
    binary: true,
    extraInput: {
      fileName: z.string().optional().describe("Attachment file name (helps pick the right text extractor)"),
    },
  },
  // ── Shared mailboxes ────────────────────────────────────────────────
  {
    name: "list-shared-mailbox-folders",
    description: "List mail folders of a shared mailbox the user has access to.",
    toolset: "shared-mail",
    scopes: ["Mail.Read.Shared"],
    method: "GET",
    path: "/users/{mailbox}/mailFolders",
    pathParamDescriptions: { mailbox: "Shared mailbox address, e.g. info@company.com" },
    resourceType: "mailFolder",
    paginated: true,
    defaultSelect: FOLDER_SELECT,
  },
  {
    name: "list-shared-mailbox-messages",
    description: "List/search messages of a shared mailbox the signed-in user has access to.",
    toolset: "shared-mail",
    scopes: ["Mail.Read.Shared"],
    method: "GET",
    path: "/users/{mailbox}/messages",
    pathParamDescriptions: { mailbox: "Shared mailbox address" },
    resourceType: "mailMessage",
    paginated: true,
    defaultSelect: MSG_LIST_SELECT,
    defaultOrderby: "receivedDateTime desc",
    query: { filter: true, search: true, orderby: true, select: true },
    timeFilterProperty: "receivedDateTime",
    kqlTime: true,
    sourceType: "mailMessage",
  },
  {
    name: "list-shared-mailbox-folder-messages",
    description: "List/search messages inside a folder of a shared mailbox.",
    toolset: "shared-mail",
    scopes: ["Mail.Read.Shared"],
    method: "GET",
    path: "/users/{mailbox}/mailFolders/{folderId}/messages",
    pathParamDescriptions: { mailbox: "Shared mailbox address", folderId: "Mail folder id" },
    resourceType: "mailMessage",
    paginated: true,
    defaultSelect: MSG_LIST_SELECT,
    defaultOrderby: "receivedDateTime desc",
    query: { filter: true, search: true, orderby: true, select: true },
    timeFilterProperty: "receivedDateTime",
    kqlTime: true,
    sourceType: "mailMessage",
  },
  {
    name: "get-shared-mailbox-message",
    description: "Get a single shared-mailbox message including its full body.",
    toolset: "shared-mail",
    scopes: ["Mail.Read.Shared"],
    method: "GET",
    path: "/users/{mailbox}/messages/{messageId}",
    pathParamDescriptions: { mailbox: "Shared mailbox address" },
    resourceType: "mailMessage",
    query: { select: true },
    sourceType: "mailMessage",
  },
  {
    name: "get-shared-mailbox-attachment-content",
    description: "Download an attachment from a shared-mailbox message (text extraction like get-mail-attachment-content).",
    toolset: "shared-mail",
    scopes: ["Mail.Read.Shared"],
    method: "GET",
    path: "/users/{mailbox}/messages/{messageId}/attachments/{attachmentId}/$value",
    pathParamDescriptions: { mailbox: "Shared mailbox address" },
    resourceType: "mailAttachment",
    binary: true,
    extraInput: {
      fileName: z.string().optional().describe("Attachment file name (helps pick the right text extractor)"),
    },
  },
];
