import type { EndpointDef } from "../types.js";

const PAGE_SELECT = "id,title,createdDateTime,lastModifiedDateTime,links,parentSection";

export const onenoteEndpoints: EndpointDef[] = [
  // â”€â”€ Personal OneNote â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    name: "list-onenote-notebooks",
    description: "List the signed-in user's OneNote notebooks.",
    toolset: "onenote",
    scopes: ["Notes.Read"],
    method: "GET",
    path: "/me/onenote/notebooks",
    resourceType: "notebook",
    paginated: true,
    skipPaging: true,
    query: { filter: true, orderby: true },
    defaultSelect: "id,displayName,createdDateTime,lastModifiedDateTime,links,isDefault",
  },
  {
    name: "get-onenote-notebook",
    description: "Get a single OneNote notebook.",
    toolset: "onenote",
    scopes: ["Notes.Read"],
    method: "GET",
    path: "/me/onenote/notebooks/{notebookId}",
    resourceType: "notebook",
  },
  {
    name: "list-onenote-notebook-sections",
    description: "List sections of a OneNote notebook (newest-modified first; paginates past 100 sections automatically).",
    toolset: "onenote",
    scopes: ["Notes.Read"],
    method: "GET",
    path: "/me/onenote/notebooks/{notebookId}/sections",
    resourceType: "onenoteSection",
    paginated: true,
    skipPaging: true,
    defaultOrderby: "lastModifiedDateTime desc",
    query: { filter: true, orderby: true },
    defaultSelect: "id,displayName,createdDateTime,lastModifiedDateTime,links",
  },
  {
    name: "list-onenote-sections",
    description: "List all OneNote sections across the user's notebooks (newest-modified first; paginates past 100 automatically).",
    toolset: "onenote",
    scopes: ["Notes.Read"],
    method: "GET",
    path: "/me/onenote/sections",
    resourceType: "onenoteSection",
    paginated: true,
    skipPaging: true,
    defaultOrderby: "lastModifiedDateTime desc",
    query: { filter: true, orderby: true },
    defaultSelect: "id,displayName,createdDateTime,lastModifiedDateTime,links,parentNotebook",
  },
  {
    name: "list-onenote-section-pages",
    description: "List pages of a OneNote section.",
    toolset: "onenote",
    scopes: ["Notes.Read"],
    method: "GET",
    path: "/me/onenote/sections/{sectionId}/pages",
    resourceType: "onenotePage",
    paginated: true,
    defaultSelect: PAGE_SELECT,
    query: { search: true, filter: true, orderby: true },
    sourceType: "onenotePage",
  },
  {
    name: "search-onenote-pages",
    description:
      "List/search OneNote pages across all notebooks (full-text $search over title and content; time filter on lastModifiedDateTime).",
    toolset: "onenote",
    scopes: ["Notes.Read"],
    method: "GET",
    path: "/me/onenote/pages",
    resourceType: "onenotePage",
    paginated: true,
    defaultSelect: PAGE_SELECT,
    query: { search: true, filter: true, orderby: true },
    timeFilterProperty: "lastModifiedDateTime",
    sourceType: "onenotePage",
  },
  {
    name: "get-onenote-page",
    description: "Get metadata of a OneNote page. Use get-onenote-page-content for the actual body.",
    toolset: "onenote",
    scopes: ["Notes.Read"],
    method: "GET",
    path: "/me/onenote/pages/{pageId}",
    resourceType: "onenotePage",
    sourceType: "onenotePage",
  },
  {
    name: "get-onenote-page-content",
    description: "Get the FULL HTML content of a OneNote page (the actual note body, not just metadata).",
    toolset: "onenote",
    scopes: ["Notes.Read"],
    method: "GET",
    path: "/me/onenote/pages/{pageId}/content",
    resourceType: "onenotePage",
    accept: "text/html",
  },
  // â”€â”€ SharePoint-hosted OneNote â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    name: "list-site-onenote-notebooks",
    description: "List OneNote notebooks hosted on a SharePoint site.",
    toolset: "onenote",
    scopes: ["Notes.Read.All", "Sites.Read.All"],
    method: "GET",
    path: "/sites/{siteId}/onenote/notebooks",
    pathParamDescriptions: { siteId: "SharePoint site id (from search-sites)" },
    resourceType: "notebook",
    paginated: true,
    skipPaging: true,
    query: { filter: true, orderby: true },
    defaultSelect: "id,displayName,createdDateTime,lastModifiedDateTime,links",
  },
  {
    name: "list-site-onenote-notebook-sections",
    description:
      "List sections of a SharePoint-hosted OneNote notebook (newest-modified first; paginates past 100 sections automatically).",
    toolset: "onenote",
    scopes: ["Notes.Read.All", "Sites.Read.All"],
    method: "GET",
    path: "/sites/{siteId}/onenote/notebooks/{notebookId}/sections",
    pathParamDescriptions: { siteId: "SharePoint site id", notebookId: "Notebook id (from list-site-onenote-notebooks)" },
    resourceType: "onenoteSection",
    paginated: true,
    skipPaging: true,
    defaultOrderby: "lastModifiedDateTime desc",
    defaultSelect: "id,displayName,createdDateTime,lastModifiedDateTime,links",
    query: { filter: true, orderby: true },
  },
  {
    name: "list-site-onenote-section-pages",
    description: "List pages of a section in a SharePoint-hosted OneNote notebook.",
    toolset: "onenote",
    scopes: ["Notes.Read.All", "Sites.Read.All"],
    method: "GET",
    path: "/sites/{siteId}/onenote/sections/{sectionId}/pages",
    pathParamDescriptions: { siteId: "SharePoint site id", sectionId: "Section id (from list-site-onenote-notebook-sections)" },
    resourceType: "onenotePage",
    paginated: true,
    defaultSelect: PAGE_SELECT,
    query: { search: true, filter: true, orderby: true },
    sourceType: "onenotePage",
  },
  {
    name: "list-site-onenote-pages",
    description: "List/search OneNote pages of a SharePoint site's notebooks.",
    toolset: "onenote",
    scopes: ["Notes.Read.All", "Sites.Read.All"],
    method: "GET",
    path: "/sites/{siteId}/onenote/pages",
    pathParamDescriptions: { siteId: "SharePoint site id" },
    resourceType: "onenotePage",
    paginated: true,
    defaultSelect: PAGE_SELECT,
    query: { search: true, filter: true, orderby: true },
    sourceType: "onenotePage",
  },
  {
    name: "get-site-onenote-page-content",
    description: "Get the FULL HTML content of a SharePoint-hosted OneNote page.",
    toolset: "onenote",
    scopes: ["Notes.Read.All", "Sites.Read.All"],
    method: "GET",
    path: "/sites/{siteId}/onenote/pages/{pageId}/content",
    pathParamDescriptions: { siteId: "SharePoint site id" },
    resourceType: "onenotePage",
    accept: "text/html",
  },
];
