import { z } from "zod";
import type { EndpointDef } from "../types.js";

const ITEM_SELECT =
  "id,name,size,webUrl,createdDateTime,lastModifiedDateTime,createdBy,lastModifiedBy,file,folder,parentReference";

export const sharepointEndpoints: EndpointDef[] = [
  {
    name: "search-sites",
    description: "Search SharePoint sites the signed-in user can access, by keyword.",
    toolset: "sharepoint",
    scopes: ["Sites.Read.All"],
    method: "GET",
    path: "/sites",
    resourceType: "site",
    paginated: true,
    sourceType: "site",
    extraInput: { query: z.string().describe("Site search keyword, e.g. project or team name") },
    buildQuery: (args) => ({ search: String(args.query) }),
  },
  {
    name: "get-site",
    description: "Get a SharePoint site by id (or 'hostname:/sites/path' form).",
    toolset: "sharepoint",
    scopes: ["Sites.Read.All"],
    method: "GET",
    path: "/sites/{siteId}",
    resourceType: "site",
    sourceType: "site",
  },
  {
    name: "list-site-drives",
    description: "List document libraries (drives) of a SharePoint site.",
    toolset: "sharepoint",
    scopes: ["Sites.Read.All"],
    method: "GET",
    path: "/sites/{siteId}/drives",
    resourceType: "drive",
    paginated: true,
    defaultSelect: "id,name,driveType,webUrl,createdDateTime,lastModifiedDateTime",
  },
  {
    name: "get-drive",
    description: "Get a drive (document library) by id.",
    toolset: "sharepoint",
    scopes: ["Sites.Read.All", "Files.Read.All"],
    method: "GET",
    path: "/drives/{driveId}",
    resourceType: "drive",
  },
  {
    name: "list-drive-root-items",
    description: "List files/folders in the root of a drive (document library).",
    toolset: "sharepoint",
    scopes: ["Files.Read.All"],
    method: "GET",
    path: "/drives/{driveId}/root/children",
    resourceType: "driveItem",
    paginated: true,
    defaultSelect: ITEM_SELECT,
    query: { filter: true, orderby: true, select: true },
    sourceType: "driveItem",
  },
  {
    name: "list-drive-folder-items",
    description: "List files/folders inside a folder of a drive.",
    toolset: "sharepoint",
    scopes: ["Files.Read.All"],
    method: "GET",
    path: "/drives/{driveId}/items/{itemId}/children",
    resourceType: "driveItem",
    paginated: true,
    defaultSelect: ITEM_SELECT,
    query: { filter: true, orderby: true, select: true },
    sourceType: "driveItem",
  },
  {
    name: "get-drive-item",
    description: "Get file/folder metadata (includes @microsoft.graph.downloadUrl for files).",
    toolset: "sharepoint",
    scopes: ["Files.Read.All"],
    method: "GET",
    path: "/drives/{driveId}/items/{itemId}",
    resourceType: "driveItem",
    sourceType: "driveItem",
  },
  {
    name: "search-drive-items",
    description: "Search files by keyword within one drive (document library).",
    toolset: "sharepoint",
    scopes: ["Files.Read.All"],
    method: "GET",
    path: "/drives/{driveId}/root/search(q='{q}')",
    pathParamDescriptions: { q: "Search keyword" },
    resourceType: "driveItem",
    paginated: true,
    defaultSelect: ITEM_SELECT,
    sourceType: "driveItem",
  },
  {
    name: "download-drive-item",
    description:
      "Download a file's content from SharePoint. DOCX/XLSX/PPTX/PDF/TXT/CSV are converted to text; other binaries come back as base64. Size-limited by MAX_DOWNLOAD_BYTES.",
    toolset: "sharepoint",
    scopes: ["Files.Read.All"],
    method: "GET",
    path: "/drives/{driveId}/items/{itemId}/content",
    resourceType: "driveItem",
    binary: true,
    extraInput: {
      fileName: z.string().optional().describe("File name (helps pick the right text extractor)"),
    },
  },
  {
    name: "list-site-lists",
    description: "List SharePoint lists of a site.",
    toolset: "sharepoint",
    scopes: ["Sites.Read.All"],
    method: "GET",
    path: "/sites/{siteId}/lists",
    resourceType: "list",
    paginated: true,
    defaultSelect: "id,displayName,name,webUrl,createdDateTime,lastModifiedDateTime,list",
  },
  {
    name: "get-site-list",
    description: "Get a SharePoint list by id.",
    toolset: "sharepoint",
    scopes: ["Sites.Read.All"],
    method: "GET",
    path: "/sites/{siteId}/lists/{listId}",
    resourceType: "list",
  },
  {
    name: "list-site-list-items",
    description: "List items of a SharePoint list including their field values.",
    toolset: "sharepoint",
    scopes: ["Sites.Read.All"],
    method: "GET",
    path: "/sites/{siteId}/lists/{listId}/items",
    resourceType: "listItem",
    paginated: true,
    query: { filter: true, expand: "fields" },
  },
  {
    name: "get-site-list-item",
    description: "Get a single SharePoint list item including field values.",
    toolset: "sharepoint",
    scopes: ["Sites.Read.All"],
    method: "GET",
    path: "/sites/{siteId}/lists/{listId}/items/{itemId}",
    resourceType: "listItem",
    query: { expand: "fields" },
  },
];
