import type { EndpointDef } from "../types.js";

export const teamsEndpoints: EndpointDef[] = [
  {
    name: "list-chats",
    description: "List the signed-in user's Teams chats (1:1, group, meeting chats).",
    toolset: "teams",
    scopes: ["Chat.Read"],
    method: "GET",
    path: "/me/chats",
    resourceType: "chat",
    paginated: true,
    maxTop: 50,
    defaultSelect: "id,topic,chatType,createdDateTime,lastUpdatedDateTime,webUrl",
    query: { filter: true, orderby: true, select: true },
  },
  {
    name: "get-chat",
    description: "Get a single chat including its members.",
    toolset: "teams",
    scopes: ["Chat.Read"],
    method: "GET",
    path: "/me/chats/{chatId}",
    resourceType: "chat",
    query: { expand: "members" },
  },
  {
    name: "list-chat-messages",
    description:
      "List messages of a chat, newest first. Supports a time range (lastModifiedDateTime filter). Keyword filtering must be done client-side or via search-m365 with entityTypes=[\"chatMessage\"].",
    toolset: "teams",
    scopes: ["Chat.Read"],
    method: "GET",
    path: "/me/chats/{chatId}/messages",
    resourceType: "chatMessage",
    paginated: true,
    maxTop: 50,
    timeFilterProperty: "lastModifiedDateTime",
    sourceType: "chatMessage",
  },
  {
    name: "get-chat-message",
    description: "Get a single chat message.",
    toolset: "teams",
    scopes: ["Chat.Read"],
    method: "GET",
    path: "/me/chats/{chatId}/messages/{messageId}",
    resourceType: "chatMessage",
    sourceType: "chatMessage",
  },
  {
    name: "list-joined-teams",
    description: "List the Microsoft Teams teams the signed-in user is a member of.",
    toolset: "teams",
    scopes: ["Team.ReadBasic.All"],
    method: "GET",
    path: "/me/joinedTeams",
    resourceType: "team",
    paginated: true,
    noTop: true,
  },
  {
    name: "get-team",
    description: "Get a team's properties.",
    toolset: "teams",
    scopes: ["Team.ReadBasic.All"],
    method: "GET",
    path: "/teams/{teamId}",
    resourceType: "team",
  },
  {
    name: "list-team-channels",
    description: "List channels of a team.",
    toolset: "teams",
    scopes: ["Channel.ReadBasic.All"],
    method: "GET",
    path: "/teams/{teamId}/channels",
    resourceType: "channel",
    paginated: true,
    noTop: true,
    query: { filter: true, select: true },
  },
  {
    name: "get-team-channel",
    description: "Get a single channel of a team.",
    toolset: "teams",
    scopes: ["Channel.ReadBasic.All"],
    method: "GET",
    path: "/teams/{teamId}/channels/{channelId}",
    resourceType: "channel",
  },
  {
    name: "list-channel-messages",
    description:
      "List messages of a team channel, newest first (Graph does not support server-side filtering here; use search-m365 for keyword search).",
    toolset: "teams",
    scopes: ["ChannelMessage.Read.All"],
    method: "GET",
    path: "/teams/{teamId}/channels/{channelId}/messages",
    resourceType: "chatMessage",
    paginated: true,
    maxTop: 50,
    sourceType: "chatMessage",
  },
  {
    name: "get-channel-message",
    description: "Get a single channel message.",
    toolset: "teams",
    scopes: ["ChannelMessage.Read.All"],
    method: "GET",
    path: "/teams/{teamId}/channels/{channelId}/messages/{messageId}",
    resourceType: "chatMessage",
    sourceType: "chatMessage",
  },
  {
    name: "list-channel-message-replies",
    description: "List replies (thread) of a channel message.",
    toolset: "teams",
    scopes: ["ChannelMessage.Read.All"],
    method: "GET",
    path: "/teams/{teamId}/channels/{channelId}/messages/{messageId}/replies",
    resourceType: "chatMessage",
    paginated: true,
    maxTop: 50,
    sourceType: "chatMessage",
  },
  {
    name: "list-team-members",
    description: "List members of a team (name, email, roles).",
    toolset: "teams",
    scopes: ["TeamMember.Read.All"],
    method: "GET",
    path: "/teams/{teamId}/members",
    resourceType: "teamMember",
    paginated: true,
  },
];
